name: 'Setup action'
runs:
    using: 'composite'

    steps:
        - name: Checkout repository 🛠️
          uses: actions/checkout@v4

        - name: Setup Node.js 🌐
          uses: actions/setup-node@v3
          with:
              node-version: 'node'
              cache: 'yarn'

        - name: Cache Yarn dependencies 🗂️
          uses: actions/cache@v3
          with:
              key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
              path: |
                  ~/.cache/yarn
                  ~/.yarn-cache
                  node_modules
                  .tsbuildinfo

        - name: Install dependencies with Yarn 📥
          run: yarn install
          shell: bash
