services:
- type: web
  name: wordle-app
  runtime: node
  repo: https://github.com/MarcLlobet/millor-primera-paraula-wordle
  plan: free
  region: oregon
  buildCommand: yarn --frozen-lockfile install && yarn build:server
  startCommand: yarn start:server
  autoDeployTrigger: commit
version: "1"
