services:
- type: web
  name: wordle-app
  runtime: node
  repo: https://github.com/MarcLlobet/millor-primera-paraula-wordle
  plan: free
  region: oregon
  buildCommand: yarn --frozen-lockfile install; yarn build:server; git add -f dirst-server
  startCommand: yarn start:server
  autoDeployTrigger: commit
  rootDir: dist-server
version: "1"
