name: Diccionari

on:
    push:
        branches:
            - main

jobs:
    diccionari:
        runs-on: ubuntu-latest
        steps:
            - name: Get remot diccionari etag
              id: diccionari-etag
              shell: bash
              run: |
                  echo "ETAG=$(curl --head --location https://github.com/Softcatala/catalan-dict-tools/raw/refs/heads/master/resultats/lt/diccionari.txt | grep -i etag)" >> $GITHUB_OUTPUT

            - name: Cache diccionary dependencies
              id: diccionari-cache
              uses: actions/cache@v3
              with:
                  path: diccionari/.etag
                  key: diccionari-${{steps.diccionari-etag.outputs.ETAG}}

            - name: Download diccionary 📥
              if: steps.diccionari-cache.outputs.cache-hit != 'true'
              shell: bash
              run: |
                  curl -o diccionari.txt https://raw.githubusercontent.com/Softcatala/catalan-dict-tools/refs/heads/master/resultats/lt/diccionari.txt
